sudo: false
language: php
php:
  - '7.1'
  - '7.2'
before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  - vendor/bin/phpcs -p --standard=PSR4 src/

after_success:
  - travis_retry bash <(curl -s https://codecov.io/bash)